
tracker.url=http://192.168.1.11:8081
origin.server.url=http://192.168.1.11:8080
client.name=win-Client-1

# Network Configuration
# Force bind to specific LAN IP to avoid VirtualBox/VMWare adapters
client.bind.address=192.168.1.11
peer.server.port=6881

# Logging
log.level=INFO
log.show.ip=true
log.show.flow=true
