# Trỏ về Máy Windows Server
tracker.url=http://192.168.1.51:8081
origin.server.url=http://192.168.1.51:8080

# Tên Client
client.name=Windows_Client-1

client.bind.address=192.168.1.51

# Các cấu hình khác
peer.server.port=6881
log.level=INFO
log.show.ip=true
log.show.flow=true


