# Trỏ về Máy Windows Server (Thay đổi IP này thành IP máy chạy Tracker/Server của bạn)
tracker.url=http://172.20.10.2:8081
origin.server.url=http://172.20.10.2:8080

# Tên Client (Nên đổi khác nhau cho từng máy nếu muốn dễ debug)
client.name=Client-Machine

# client.bind.address=172.20.10.11 
# LƯU Ý: Đã comment dòng trên để dùng Auto-Detection. 
# Nếu bỏ comment nhưng IP không đúng, Client sẽ tự kết nối chính mình -> Lỗi Loop!

# Các cấu hình khác
peer.server.port=6881
log.level=INFO
log.show.ip=true
log.show.flow=true
